version: '2'

services:
 dokuwiki:
   container_name: dokuwiki
   build:
     context: .
     dockerfile: Dockerfile
   ports:
    - "8080:8080"
   volumes:
    - "dokuwiki_data:/usr/share/dokuwiki"

volumes:
  dokuwiki_data:
    driver: local
